name: jtWar
version: 1.2.2
author: jamietech
description: "All-in-one plugin to enable a server administrator to create a server for players to battle in. Also contains fun admin commands!"
website: http://dev.nekotech.tk
main: tk.nekotech.war.War
load: startup
commands:
  war:
    description: "Information about the plugin"
    usage: /<command>
  join:
    description: "Auto-assign to a team"
    usage: /<command>
  blu:
    description: "Sets blu spawn point"
    usage: /<command>
  red:
    description: "Sets red spawn point"
    usage: /<command>
  ready:
    description: "Toggles server ready mode"
    usage: /<command>
  spectate:
    description: "Sets spectator spawn point"
    usage: /<command>
  reset:
    description: "Resets most config options"
    usage: /<command>
  admin:
    description: "Enter administrator mode"
    usage: /<command> [a/announce]
  kick:
    description: "Kicks player"
    usage: /<command> <player> <reason>
    aliases: ['k']
  ban:
    description: "Bans player"
    usage: /<command> <player> <reason>
    aliases: ['b']
  unban:
    description: "Unbans player"
    usage: /<command> <player>
    aliases: ['pardon']
  smite:
    description: "Judge player"
    usage: /<command> <player>
    aliases: ['s']